### ISSUE TITLE
Quest2 view recenter

### ISSUE THREAD

**Issue by davoodkharmanzar** [basti564/vrLauncher#12]
hi dear,
my question is not related to VRLauncher !!

but does exists a method to direct call **Recenter View** by code?? 

i mean the function of this button but inside our app :]

![recenter](https://user-images.githubusercontent.com/10723167/125437713-9e37a596-2e04-42fd-a62f-515719e651cc.jpg)

**Comment by ptrpaws** [comment]
Hello,
probably not, the buttons use a different method of starting events and it would take quite some time to reverse engineer it.
I will let you know when I have found a solution.
I'm sorry that I don't know how to help you.
Have a nice day :)

(Closing this issue because it's unrelated to the vrLauncher project)
